### ISSUE TITLE
self-hosted: webapp can't start without fileserver

### ISSUE THREAD

**Issue by awoimbee** [allegroai/clearml-server#176]
As I understand it, the fileserver is not needed if one prefers to use another storage medium (like s3).
And since the self-hosted file server is unsecure, I prefer to not use it.

But the webapp requires `NGINX_FILESERVER_ADDRESS`.
If `NGINX_FILESERVER_ADDRESS` is set to `clearml-fileserver` but `clearml-fileserver` does not exist (which is what the helm chart does when `fileserver.enabled=false`), nginx doesn't start:
```
2023/01/20 11:27:41 [emerg] 38#38: host not found in upstream "clearml-fileserver" in /etc/nginx/nginx.conf:88
nginx: [emerg] host not found in upstream "clearml-fileserver" in /etc/nginx/nginx.conf:88
```

The workaround I use is to set `NGINX_FILESERVER_ADDRESS` to a bogus but existing address (`clearml-apiserver`).

**Comment by awoimbee** [comment]
Well, I deployed without a file server, it seems to work 🙈

**Comment by jkhenning** [comment]
@awoimbee the `NGINX_FILESERVER_ADDRESS` is basically used to set up the reverse proxy serving the WebApp, so bogus values (as long as you don't use them 🙂) will work 👍

**Comment by lucasvandijck** [comment]
Is there any work being done to fix this issue? I am currently hosting a dummy site to circumvent the issue, but that can't be a good solution:

1. Set the fileserver.enabled value to false
2. Deploy a fake fileserver using hashicorp/http-echo
```

apiVersion: v1
kind: Pod
metadata:
  name: clearml-fileserver
  namespace: flux-deployments
spec:
  containers:
  - name: hello-world-container
    image: hashicorp/http-echo
    args:
    - "-text=Hello, World!"
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clearml-fileserver
  namespace: flux-deployments
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
```
