### ISSUE TITLE
Nginx Not Loading Plotly.js Resource: ClearML Self-Hosted Docker 

### ISSUE THREAD

**Issue by Betagmr** [allegroai/clearml-server#227]
# Nginx Not Loading Plotly.js Resource: ClearML Self-Hosted Docker 

I have deployed a self-hosted instance of Clearml on Ubuntu 20.04 virtual machine with Docker. Initially, everything was working as expected, and I could view plots and scalars on the web-ui without any problems. However, at some point, the ui stop showing plots and scalars. As you can see in Image 2, the Plotly resource is not loading. It seems that Nginx is refusing to serve the file containing the Plotly JavaScript. The only change I made on Docker-Compose file was disabling the binding with IPv6.

<div>
  <img src="https://github.com/allegroai/clearml-server/assets/30557346/963da522-c011-4d30-9975-1ba48a4a7d07" alt="Image" width="300" height="300">
  
  <img src="https://github.com/allegroai/clearml-server/assets/30557346/f600ea8d-ae46-40a9-9e81-e725dd1e0036" alt="Image" width="600" height="300">
</div>

**Comment by Betagmr** [comment]
Hi @shyallegro,
I'm using docker compose to serve the UI. 
I disabled the nginx IPv6 binding by adding an environment variable.
Here is my Docker Compose configuration on the webserver, the rest remains the same.

```yml
webserver:
  command:
    - webserver
  container_name: clearml-webserver
  environment:
    - DISABLE_NGINX_IPV6=true
  #  CLEARML_SERVER_SUB_PATH : clearml-web # Allow Clearml to be served with a URL path prefix.
  image: allegroai/clearml:latest
  restart: unless-stopped
  depends_on:
    - apiserver
  ports:
    - "8080:80"
  networks:
    - backend
    - frontend
```
