### ISSUE TITLE
How to limit parallel job per queue + user permission Q

### ISSUE THREAD

**Issue by amir-bialek** [allegroai/clearml-server#249]
Hey all, I couldn't find any reference for the following issues in the documentation and will greatly appreciate your help.

Deployed clearml Server + Agent on-pem K8S via helmchart
```
clearml:
  defaultCompany: "imagry"

nameOverride: "clearml"
fullnameOverride: "clearml"

apiserver:
  existingAdditionalConfigsSecret: "dev-clearml-extraconfig-secret"
  service:
    port: 8008

fileserver:
  service:
    type: ClusterIP
    port: 8081

webserver:
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    ingressClassName: "imagry-on-prem"
    hostName: "clearml.imagry.dev"
    tlsSecretName: "clearml-dev-cert"
    annotations: {}
    path: "/"
```

Working well, can see the UI + agent is connected and listen on queue.

Every time I send a new run to the queue, the agent lift another pod that run in parallel.
Is it possible to limit the queue or agent for running only 2 tasks / job in parallel?

I am able to create severals users via  dev-clearml-extraconfig-secret however they are all admins. How can I change the roles so one of them will be only readers?

In addition, I will like to create the queue via the helmchart, so when clearml-server start some queues will be ready-made. Anyone know if this is possible?

Thank you.
