### ISSUE TITLE
Incorrect parsing of WEBSERVER__fileBaseUrl

### ISSUE THREAD

**Issue by Danie1Nash** [allegroai/clearml-server#271]
### Description
According to the official documentation from version v1.16.0, when the file server is configured on a domain different from that of the web server and token authentication is enabled on the file server, it is required to configure the WebApp to use a proxy server when accessing the file server:
```yaml
services:  
  webserver:  
    environment:  
      WEBSERVER__fileBaseUrl: "https://files.<my_domain>/"  
      WEBSERVER__useFilesProxy: true
```
src: https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_config/#subdomain-configuration

However, when using this setting on the web server side, the following error is produced:
```
Error parsing WEBSERVER_fileBaseUrl JSON value 'https://files.<my_domain>/': Expecting value: line 1 column 1 (char 0)
```

### Problem Investigation
It is presumed that this error occurs as a result of the execution of the script `docker/build/internal_files/update_from_env.py`, which is responsible for updating the JSON configuration based on environment variables with a fixed prefix. The snippet of code that produces the error is shown below:
```python
def parse_value(k, v):
	try:
		return json.loads(v)
	except json.JSONDecodeError as ex:
		print(f"Error parsing {k} JSON value `{v}`: {str(ex)}")
		exit(2)

prefix = args.prefix + args.sep

env_vars = {
	k.lstrip(prefix): parse_value(k, v) if args.parse_env else v
	for k, v in environ.items() if k.startswith(prefix)
}
```

When executing `json.loads(v)`, the corresponding error is raised:
```python
>>> import json 
>>> result = json.loads("https://files.<my_domain>/")
# json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Proposed Solution
To work around this issue, I had to additionally escape the variable by enclosing it in quotes when defining the environment variables:

```yaml
services:  
  webserver:  
    environment:  
      WEBSERVER__fileBaseUrl: '"https://files.<my_domain>/"'
      WEBSERVER__useFilesProxy: true
```

Then `json.loads(v)` works correctly:
```python
>>> import json 
>>> result = json.loads('"https://files.<my_domain>/"')
>>> result
'https://files.<my_domain>/'
```

### Discussion
Currently, the documentation is misleading. It might be worth considering either modifying the documentation or addressing the issue at the `update_from_env.py` level.

### Environment
- **ClearML Server:** 2.0.0
### Related Issues
- https://github.com/clearml/clearml-server/issues/248
